/*
 * This file is generated by jOOQ.
 */
package me.vmorozov.orm.playground.domain;

public class Company {

    private Integer id;
    private String  name;

    public Company() {}

    public Company(Company value) {
        this.id = value.id;
        this.name = value.name;
    }

    public Company(
        Integer id,
        String  name
    ) {
        this.id = id;
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }

    public Company setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Company setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String toString() {
        return "Company{" +
            "id=" + id +
            ", name='" + name + '\'' +
            '}';
    }
}
