/*
 * This file is generated by jOOQ.
 */
package me.vmorozov.orm.playground.domain;


import javax.validation.constraints.NotNull;

public class Department {

    private Integer id;
    private Integer headId;
    private Integer companyId;
    private String  name;

    public Department() {}

    public Department(Department value) {
        this.id = value.id;
        this.headId = value.headId;
        this.companyId = value.companyId;
        this.name = value.name;
    }

    public Department(
        Integer id,
        Integer headId,
        Integer companyId,
        String  name
    ) {
        this.id = id;
        this.headId = headId;
        this.companyId = companyId;
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }

    public Department setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getHeadId() {
        return this.headId;
    }

    public Department setHeadId(Integer headId) {
        this.headId = headId;
        return this;
    }

    @NotNull
    public Integer getCompanyId() {
        return this.companyId;
    }

    public Department setCompanyId(Integer companyId) {
        this.companyId = companyId;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Department setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String toString() {
        return "Department{" +
            "id=" + id +
            ", headId=" + headId +
            ", companyId=" + companyId +
            ", name='" + name + '\'' +
            '}';
    }
}
