/*
 * This file is generated by jOOQ.
 */
package me.vmorozov.orm.playground.domain;

import javax.validation.constraints.NotNull;
import java.io.Serializable;

public class Employee implements Serializable {

    private static final long serialVersionUID = 629676349;

    private Integer id;
    private Integer departmentId;
    private String  name;
    private String  position;

    public Employee() {}

    public Employee(Employee value) {
        this.id = value.id;
        this.departmentId = value.departmentId;
        this.name = value.name;
        this.position = value.position;
    }

    public Employee(
        Integer id,
        Integer departmentId,
        String  name,
        String  position
    ) {
        this.id = id;
        this.departmentId = departmentId;
        this.name = name;
        this.position = position;
    }

    public Integer getId() {
        return this.id;
    }

    public Employee setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    public Integer getDepartmentId() {
        return this.departmentId;
    }

    public Employee setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Employee setName(String name) {
        this.name = name;
        return this;
    }

    public String getPosition() {
        return this.position;
    }

    public Employee setPosition(String position) {
        this.position = position;
        return this;
    }

    @Override
    public String toString() {
        return "Employee{" +
            "id=" + id +
            ", departmentId=" + departmentId +
            ", name='" + name + '\'' +
            ", position='" + position + '\'' +
            '}';
    }
}
